# Generated by Django 5.2.7 on 2025-10-25 05:15

import tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='note',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='link',
            name='slug',
            field=models.SlugField(default=tracker.models.make_slug, unique=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='target_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
