# Generated by Django 5.2.7 on 2025-10-25 05:28

import tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_link_note_alter_link_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='click',
            options={'ordering': ['-ts']},
        ),
        migrations.RemoveField(
            model_name='click',
            name='raw_headers',
        ),
        migrations.RemoveField(
            model_name='click',
            name='referer',
        ),
        migrations.RemoveField(
            model_name='link',
            name='active',
        ),
        migrations.RemoveField(
            model_name='link',
            name='target_url',
        ),
        migrations.AlterField(
            model_name='link',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='slug',
            field=models.CharField(default=tracker.models.make_slug, max_length=32, unique=True),
        ),
    ]
