# Generated by Django 5.2.7 on 2025-10-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_click_options_remove_click_raw_headers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='case_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
