# Generated by Django 5.2.7 on 2025-10-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_link_case_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='click',
            name='country',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='click',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='click',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='click',
            name='region',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
